### ISSUE TITLE
Update to mbed core 2.2.0

### ISSUE THREAD

**Issue by fabianoriccardi** [platformio/platform-raspberrypi#15]
Hi,

the official core version 2.2.0 has been released: will you upgrade to it? https://github.com/arduino/ArduinoCore-mbed/releases/tag/2.2.0

**Comment by maxgerhardt** [comment]
Meanwhile v2.3.1 has been released. https://github.com/arduino/ArduinoCore-mbed/releases/tag/2.3.1

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-raspberrypi/commit/128a0826e1783a9103373c2878dbc43ebc0e7f88. Please retest with the upstream version:
```ini
[env:nanorp2040connect]
platform = https://github.com/platformio/platform-raspberrypi.git
framework = arduino
board = nanorp2040connect
```
