### ISSUE TITLE
Update for ArduinoCore-mbed

### ISSUE THREAD

**Issue by sstaub** [platformio/platform-raspberrypi#17]
Can you please update the ArduinoCore-mbed to v2.4.1

**Comment by valeros** [comment]
Updated, please retest with the [upstream version](https://docs.platformio.org/en/latest/platforms/raspberrypi.html#upstream) of the platform.

**Comment by sstaub** [comment]
Can compile. If I want to use the upstream version I have to update manually the platform. Is this intended?
When I change to upstream version, I think the new files should automatically updated, when changing the .ini and first compile or build.

**Comment by valeros** [comment]
> If I want to use the upstream version I have to update manually the platform. Is this intended?

No, it's not. PlatformIO should handle your platform specification in the `platformio.ini` file automatically.

**Comment by sstaub** [comment]
Maybe a bug?
I changed the platform to
platform = https://github.com/platformio/platform-raspberrypi.git
but when I build the old version was used. I'm using autosave for the files.

**Comment by valeros** [comment]
Please attach here your `platformio.ini`.

**Comment by sstaub** [comment]
```
[env:pico]
#platform = raspberrypi
platform = https://github.com/platformio/platform-raspberrypi.git
board = pico
framework = arduino
```

**Comment by valeros** [comment]
Probably you have multiple `raspberrypi` platforms installed in your system. Are there any suspicious folders with the `raspberrypi@hash` suffix in `~/.platformio/platforms`? If so, you can either delete them or run `pio platform update raspberrypi` to pull the latest changes.

**Comment by sstaub** [comment]
Ok, it seems I was too fast. Maybe I started building while a background task was running. Cleaned the piofolder and tried again, now it works. Thank You
