### ISSUE TITLE
Update ArduinoCore-mbed

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-raspberrypi#19]
Currently the platform is using version "~2.4.0", which is currently 2.4.1

https://github.com/platformio/platform-raspberrypi/blob/76011726a908c35a598109b127f3a1a638d7885a/platform.json#L34-L39

https://github.com/arduino/ArduinoCore-mbed/releases has 2.5.2 released.

**Comment by valeros** [comment]
Updated in [v1.4.0](https://github.com/platformio/platform-raspberrypi/releases/tag/v1.4.0).
