### ISSUE TITLE
setup1() and loop1() not being called 

### ISSUE THREAD

**Issue by Caian** [platformio/platform-raspberrypi#47]
I'm trying to run this simple multicore program on RP2040: https://github.com/earlephilhower/arduino-pico/blob/master/libraries/rp2040/examples/Multicore/Multicore.ino 

But core1 messages are never being printed.

I'm on PlatformIO 3.1.1 (2023-03-16) and have the following packages:

```
 - framework-arduino-mbed @ 3.5.4 
 - tool-rp2040tools @ 1.0.2 
 - toolchain-gccarmnoneeabi @ 1.90201.191206 (9.2.1)
```

**Comment by savejeff** [comment]
How does your platformio.ini look like? 
Could You please post your code as well if it's not too much. 
Oi use the dual core with no problem
