### ISSUE TITLE
Support for iLabs Challenger boards

### ISSUE THREAD

**Issue by sjdevlin** [platformio/platform-raspberrypi#53]
- [X ] **Feature Request**.

Please can you consider adding support for the iLabs Challenger series of RP2040 dev boards.  Thank you

**Comment by LinusHeu** [comment]
The arduino-mbed core (used in this platformio platform) only supports the Arduino Nano RP2040 connect and the Raspberry Pi Pico W.
The unofficial arduino-pico core supports the iLabs Challenger series and many more.
https://github.com/earlephilhower/arduino-pico
https://arduino-pico.readthedocs.io/en/latest/platformio.html

**Comment by sjdevlin** [comment]
Thank you for the info !
