### ISSUE TITLE
Windows: "This device cannot start. (Code 10)"

### ISSUE THREAD

**Issue by Caian** [platformio/platform-raspberrypi#58]
I have a code for a simple macro pad using the raspberry platform with arduino framework, and it uses the PluggableUSBHID, USBKeyboard and USBMouse that are included with the framework, plus the Serial is also printing through USB.

It works fine on Linux, but Windows 10/11 fails to start the device with a STATUS_DEVICE_DATA_ERROR code.

I saw similar issues with pico-sdk and a workaround for a hardware bug that manually sleeps for 800us, but I haven't seen anything for PlatformIO.

Is there anything I'm missing?

**Comment by valeros** [comment]
Hi @Caian, it seems that your problem has nothing to do with PlatformIO itself, probably there is an issue with Arduino framework or Windows drivers for your device which is out of scope for this repository.
