### ISSUE TITLE
-DF_CPU missing

### ISSUE THREAD

**Issue by blackketter** [platformio/platform-raspberrypi#6]
I believe that `build_flags` should include  `-DF_CPU=133000000` by default for the RP2040 boards.  

I see that "f_cpu" is defined in the pico.json file, but that doesn't seem to propagate down to the compiler flags.

**Comment by valeros** [comment]
Hi @blackketter ! There is no such  macro in the official repo https://github.com/arduino/ArduinoCore-mbed/blob/master/variants/RASPBERRY_PI_PICO/defines.txt

**Comment by blackketter** [comment]
Thanks, @valeros !  So would this be a bug against the ArduinoCore-mbed?  It seems to be defined for every other Arduino board I've checked...

**Comment by valeros** [comment]
> So would this be a bug against the ArduinoCore-mbed?

I think so, but that macro doesn't seem to be very widely used with Arm-based boards.
